### ISSUE TITLE
zero-shot code

### ISSUE THREAD

**Issue by xxllp** [PlusLabNLP/DEGREE#2]

**Comment by ihungalexhsu** [comment]
Hi,

Since the zero-shot results are not presented in the main content of the paper, we didn't organize it at least for now. We might update the zero-shot code afterward. But if you want to have a glance at the zero-shot functions we use, the most important feature is to use the "unseen_types" argument in data.py. Please check whether this info is helpful.

Thanks.

**Comment by xxllp** [comment]
I see，thank for you answer~
